### ISSUE TITLE
ImportError: No module named cdd

### ISSUE THREAD

**Issue by Yanxing-Shi** [hungpham2511/rapid-transport#1]
Hello, I made the following mistakes in the replication experiment：
$ python scripts/generate_contact_constraint.py
Traceback (most recent call last):
  File "scripts/generate_contact_constraint.py", line 1, in <module>
    import cdd
ImportError: No module named cdd
My system is configured as ubuntu16.04，Please help me out, thank you very much

**Comment by hungpham2511** [comment]
Did you follow the installation instructions? That error message means you have not installed pycddlib.

Bests,

Hung

________________________________
